// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK-pMBfUEejgSPhXG_3Qh7TQObnQj_ok8',
    appId: '1:453027768158:web:e179081af5ab485eb2d1cf',
    messagingSenderId: '453027768158',
    projectId: 'carparking-922c3',
    authDomain: 'carparking-922c3.firebaseapp.com',
    storageBucket: 'carparking-922c3.appspot.com',
    measurementId: 'G-CHYH769KM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFC6rvh00E6RvSmpetPa3EDGm_vDIj-Wc',
    appId: '1:453027768158:android:aac2f56e14322b10b2d1cf',
    messagingSenderId: '453027768158',
    projectId: 'carparking-922c3',
    storageBucket: 'carparking-922c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu3M-CRPWpwHoUBwRigdRhoi_Po6zN0kc',
    appId: '1:453027768158:ios:0b00cd0ab33d7968b2d1cf',
    messagingSenderId: '453027768158',
    projectId: 'carparking-922c3',
    storageBucket: 'carparking-922c3.appspot.com',
    iosBundleId: 'com.example.carparking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu3M-CRPWpwHoUBwRigdRhoi_Po6zN0kc',
    appId: '1:453027768158:ios:0b00cd0ab33d7968b2d1cf',
    messagingSenderId: '453027768158',
    projectId: 'carparking-922c3',
    storageBucket: 'carparking-922c3.appspot.com',
    iosBundleId: 'com.example.carparking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK-pMBfUEejgSPhXG_3Qh7TQObnQj_ok8',
    appId: '1:453027768158:web:5f622348970cd47bb2d1cf',
    messagingSenderId: '453027768158',
    projectId: 'carparking-922c3',
    authDomain: 'carparking-922c3.firebaseapp.com',
    storageBucket: 'carparking-922c3.appspot.com',
    measurementId: 'G-LDHRFHEL3F',
  );
}
